Catch expected exception from `container()`
When it fails to convert, `ValueError` will be raised, not `TypeError`

```
>>> dict('1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```