fix: add workaround to make pycodestyle works
It seems that newer version of pycodestyle does not work well because of
some backword compatibilities were lost and it causes the following
exception when to run flake8 in python 3.7 envrionment:

        AttributeError: 'module' object has no attribute
        'break_around_binary_operator'

So I decided to stick the version of pycodestyle to the older version
until this issue was resolved. See also:
https://github.com/PyCQA/pycodestyle/issues/741